---
- name: Maintenance
  hosts: localhost
  tasks:
  
    - name: apt update
      apt:
        update_cache: yes

    - name: apt upgrade
      apt:
        name: "*"
        state: latest

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
