---
- name: Installing common used tools
  hosts: localhost
  tasks:
    - name: Install common used tools
      apt:
        pkg: 
          - nvtop
          - psmisc
          - htop
          - iftop
          - iotop
          - vim
          - curl
          - wget
          - cowsay
          - figlet
          - beep
          - vlc
          - rsync
          - git
          - flameshot
          - caffeine
        state: latest
        update_cache: yes
